// Builds lib/context/pack.json from Luke's Lanna context pack (people/luke/lanna-context).
// Keeps Trusted entries only (high or medium confidence) and only the fields the app uses.
// Run: node scripts/build-pack.mjs
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const SRC = join(here, "../../people/luke/lanna-context");
const OUT = join(here, "../lib/context/pack.json");

const load = (f) => JSON.parse(readFileSync(join(SRC, f), "utf8"));
const trusted = (x) => x.confidence === "high" || x.confidence === "medium";

const dishes = load("northern_dishes.json")
  .filter(trusted)
  .map((d) => ({
    id: d.id,
    thai: d.thai ?? null,
    thaiNorthern: d.kham_mueang_thai ?? null,
    name: d.rtgs,
    english: d.english,
    description: d.description,
    ingredients: d.key_ingredients ?? [],
    season: d.season ?? null,
    occasion: d.occasion ?? null,
    source: d.source,
  }));

const produce = load("seasonal_produce.json")
  .filter(trusted)
  .map((p) => ({
    id: p.id,
    thai: p.thai ?? null,
    thaiNorthern: p.kham_mueang_thai ?? null,
    name: p.rtgs,
    english: p.english,
    category: p.category,
    months: p.months ?? [],
    eatenIn: p.northern_dishes ?? [],
    source: p.source,
  }));

const sound = load("sound_correspondences.json");
const falseFriends = sound.false_friends.filter(trusted).map((f) => ({
  thai: f.northern,
  meaningHere: f.northern_meaning,
  meaningCentral: f.central_meaning,
  source: f.source,
}));

const words = load("kham_mueang_glossary.json")
  .filter((w) => trusted(w) && w.kham_mueang_thai_script)
  .map((w) => ({
    thai: w.kham_mueang_thai_script,
    roman: w.kham_mueang_roman,
    centralThai: w.central_thai,
    english: w.english,
    category: w.category,
    note: w.usage_note ?? null,
    source: w.source,
  }));

const months = load("climate_by_month.json").map((m) => ({
  month: m.month,
  season: m.season,
  highC: m.avg_high_c,
  lowC: m.avg_low_c,
  rainyDays: m.rainy_days,
  humidity: m.avg_humidity_pct,
  air: m.air_quality_note,
  talk: m.what_locals_talk_about,
}));

const festivals = load("festival_calendar.json")
  // Royal days are left out: the monarchy is a topic to avoid in small talk.
  .festivals.filter((f) => trusted(f) && f.id !== "royal_national_days")
  .flatMap((f) =>
    f.dates_2026_2027.map((d) => ({
      id: f.id,
      name: f.name,
      thai: f.thai,
      start: d.start,
      end: d.end,
      estimated: d.estimated,
      what: f.what_happens,
      alcoholBan: Boolean(f.alcohol_ban),
    })),
  )
  .sort((a, b) => a.start.localeCompare(b.start));

const place = load("places.json").places.find((p) => p.id === "warorot");

const pack = {
  about:
    "Generated by scripts/build-pack.mjs from people/luke/lanna-context. Trusted entries only. Do not edit by hand: edit overlay.ts or rerun the script.",
  place: {
    id: place.id,
    name: place.name_en,
    thai: place.name_th,
    knownFor: place.known_for,
    signatureFoods: place.signature_foods,
  },
  dishes,
  produce,
  words,
  falseFriends,
  months,
  festivals,
};

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, JSON.stringify(pack, null, 1) + "\n");
console.log(
  `pack.json: ${dishes.length} dishes, ${produce.length} produce, ${words.length} words, ${falseFriends.length} false friends, ${festivals.length} festival dates`,
);
